### PR TITLE
Added Docker support

### PR DESCRIPTION
**Pull request by denverquane**
Docker support allows images to be built and run, regardless of operating system (Docker engine is available for Mac, Linux, Windows, etc), and ran very easily once built. It also makes running multiple copies of the same application very simple, reduces compile sizes, and numerous other advantages. Hope you like it!

### CODE REVIEW

**Comment by bruno-chavez** [comment]
Hey there sorry that I ignored your PR!, I'm in the middle of my finals if you give me two weeks I can give a proper review of this, gave it a quick look the other day and seemed like all was in order, didn't get a chance to test the container tho! Sorry for the inconvenience, if I don't reply by next Sunday feel free to write a message.

**Comment by denverquane** [comment]
@bruno-chavez No worries! Sorry to rush you, I was just experimenting with pull requests and being able to contribute to other Go projects on Github :) No rush at all, hope finals went/go well!

**Comment by bruno-chavez** [comment]
I wanted to test your fork remotely before merging and when I tried to build it I got the following:

```
$ sudo docker build -f Dockerfile https://github.com/denverquane/ancestorquotes
Downloading build context from remote url: https://github.com/denverquane/ancestorquotes   81.9kB
Sending build context to Docker daemon  83.46kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: <!DOCTYPE
```

Looks like something is wrong with the dockerfile.

Oh and I did passed my finals, thanks!

**Comment by denverquane** [comment]
@bruno-chavez Try using `sudo docker build github.com/denverquane/ancestorquotes` (remove the https). Github seems to respond asking for login credentials if you hit the https:// endpoint, and then docker doesn't know how to parse it. If that doesn't work, perhaps try cloning the repo and running docker build from within the repo directory?

**Comment by bruno-chavez** [comment]
I made it work! not sure what happened before, anyway thanks for the help! everything works like a charm.

**Pull request merged**
